delaneymiranda1/futbol

- lib/stat_tracker.rb
- spec/stat_tracker_spec.rb
Wrote highest total score test and method to pass for the first 10 pieces of data from the games csv.
> feat: highest total score test and method passing

- lib/stat_tracker.rb
- spec/stat_tracker_spec.rb
Update to include Game Statistics - percentage_home_wins method and test
> Implement: #percentage_home_wins test and method

- lib/stat_tracker.rb
- spec/stat_tracker_spec.rb
Wrote #percentage_visitor_wins method and tests to pass for the full games csv data set.
> Feat: StatTracker #percentage_visitor_wins test and method

- lib/stat_tracker.rb
- spec/stat_tracker_spec.rb
In this one I did take(67) so we could test for a couple different seasons (the first 58 lines are all one season). I was running into a nomethod error for nil class originally, until i set the hash to default as an empty array. Then same as my highest score method I iterated through the game data to get the total scores. I used the hash method ".transform_values" to iterate over each of those total scores under the same season key.and calculate the average. I am sure this will need refactoring.
> Feat: average goals by season test and method

- data/game_teams.csv
- lib/stat_tracker.rb
- spec/stat_tracker_spec.rb
This pull request will add the test for StatTracker #average_goals_per_game, and implement this method by passing those tests
> Feat stat tracker #average goals per game

- lib/stat_tracker.rb
- spec/stat_tracker_spec.rb
This pull request will add the test for StatTracker #count_of_teams, and implement this method by passing those tests
> Feat stat tracker #count of teams

- lib/stat_tracker.rb
- spec/stat_tracker_spec.rb
This pull request will add the passing test and method for StatTracker #percentage_ties.
> Feat: StatTracker #percentage_ties

- lib/stat_tracker.rb
- spec/stat_tracker_spec.rb
This will add the lowest scoring home team method and fix the merging issues and order displacements.
> Feat stat tracker #lowest scoring home team

- lib/stat_tracker.rb
- spec/stat_tracker_spec.rb
This pull request will implement #lowest_scoring_visitor and required helper methods. Helper methods require proper tests, but #lowest_scoring_visitor is fully functional.
> Feat stat tracker #lowest scoring visitor

- lib/stat_tracker.rb
- spec/stat_tracker_spec.rb
This pull request implements #highest_scoring_visitor and helper methods. I had to go back and rename some of my helper methods because they were very similar - just minor differences to other helper methods. We can go back and refactor and consolidate as needed later on. I still need to test these helper methods.
> Feat: StatTracker #highest_scoring_visitor

- lib/stat_tracker.rb
- spec/stat_tracker_spec.rb
Add test and methods for #least_accurate_team, #teams_shots_goals_ratio & #total_shots
> Feat stat tracker #least accurate team

- lib/stat_tracker.rb
- spec/stat_tracker_spec.rb
This pull request will implement StatTracker #most_accurate_team.
I think we're all creating helper methods that are accomplishing a lot of the same thing, but we can go through and find those/determine which one is the best and most efficient later.
> Feat stat tracker #most accurate team

- lib/stat_tracker.rb
- spec/stat_tracker_spec.rb
This will add the test and working method for winningest coach (by given season).
> Feat stat tracker #winningest coach

- lib/stat_tracker.rb
- spec/stat_tracker_spec.rb
This will add the test and the method for worst coach. I feel like there may be a way to simplify it  since it is so similar to winningest coach but I will worry about that in the refactor if need be.
> Feat stat tracker #worst coach

- lib/stat_tracker.rb
- spec/stat_tracker_spec.rb
This pull request implements #most_tackles(season) and #fewest_tackles(season). I used two helper methods in this branch that were already merged into main.
> Feat: StatTracker #most_tackles #fewest_tackles

- .gitignore
- lib/all_season_data.rb
- lib/single_season_data.rb
- lib/stat_tracker.rb
- spec/all_season_data_spec.rb
- spec/spec_helper.rb
- spec/stat_tracker_spec.rb
This pull request will:
Create file skeleton for-
AllSeasonData
SingleSeasonData
Create initialization process for creating all relevant objects needed by StatTracker
> Refactor skeleton

- lib/stat_tracker.rb
- spec/spec_helper.rb
This will reorganize the methods and helper methods.
> feat: reorganized methods and helper methods

- data/games copy.csv
- lib/stat_tracker.rb
- spec/stat_tracker_spec.rb
This update reorganized helper methods and reduced duplicates.
> Update and reduce helper methods

- lib/all_season_data.rb
- lib/single_season_data.rb
- lib/stat_tracker.rb
- lib/team.rb
- lib/team_season.rb
- runner.rb
- spec/spec_helper.rb
This pull requests attempts a refactor to limit the amount of iteration performed by the program. This will reduce the amount of time it takes for the program to be run through the spec harness, although it is a little heavier upon initialization.
> Add team_season class and memoization to be able to run spec_harness

- lib/stat_tracker.rb
- lib/team.rb
- lib/team_season.rb
- runner.rb
This pull will show the highest total score, lowest total score and average goals by season methods refactored to be more concise.
> refactor: shorten highest and lowest total score methods

- lib/stat_tracker.rb
- lib/team.rb
- lib/team_season.rb
- runner.rb
This pull request shortens #percentage_ties and #percentage_visitor wins. I still have the previous methods commented out.
> Feat: Refactor #percentage_ties and #percentage_visitor_wins

- lib/all_season_data.rb
- lib/stat_tracker.rb
This pull request refactors #worst_offense, #highest_scoring_visitor and #lowest_scoring_visitor. Added one helper method AllSeasonData #visitor_team_score_average.
> Refactor: #worst_offense, #highest_scoring_visitor and #lowest_scoring_visitor

- lib/all_season_data.rb
- lib/stat_tracker.rb
This pull request refactors #most_tackles(season_id) and #fewest_tackles(season_id). Added one helper method and commented out the previous helper methods not being used.
> Refactored #most_tackles(season_id) and #fewest_tackles(season_id)

- spec/game_spec.rb
These are the tests for the game object class. This is testing for game info and half game info.
> test: adds test for game objects

- lib/single_season_data.rb
- lib/stat_tracker.rb
This pull request will - 
Refactor #winningest_coach(season) and #worst_coach(season) to work with the new prebuilt dataset and objects
> Refactor winningest and worst coach to work with new dataset

- lib/all_season_data.rb
- lib/stat_tracker.rb
- spec/stat_tracker_spec_copy.rb
This updates #season_accuracy, #season_tackles and #average_goals_per_game to pass spec harness test
> Spec harness test

- spec/team_season_spec.rb
These are the passing tests for the team season for a given team and for a given season.
> Test stat tracker #teamseason test

- spec/all_season_data_spec.rb
This will feature the passing tests for all season data.
> test: add tests running for all season data

- lib/all_season_data.rb
- lib/coach.rb
- lib/game.rb
- lib/require_helper.rb
- lib/single_season_data.rb
- lib/stat_tracker.rb
- lib/team.rb
- lib/team_season.rb
This pull request allows the program to be run with the test harness
> Change require statements to work with test harness
